### ISSUE TITLE
Thoughts on a shiny gadget for rpkg

### ISSUE THREAD

**Issue by rpodcast** [metacran/rpkg#15]
I see a lot of potential for `rpkg` to bring managing packages in R to another level.  I just attended [rstudio::conf](https://www.rstudio.com/conference/) and one of the lightning talks was about the [shiny gadget](http://shiny.rstudio.com/articles/gadgets.html) called [ggedit](https://github.com/metrumresearchgroup/ggedit), easily one of the best gadgets I've seen.  Anyway I think a shiny gadget that serves as a front end to this package could make for a very powerful UI.  I'd be glad to contribute (I've worked with shiny ever since it was first released), but I wanted to check with you first and see if you agree with this or if you had a different vision for this package.

**Comment by gaborcsardi** [comment]
Hi, this is an unfinished, abandoned project. I am sorry that this is not apparent from the repo.

**Comment by rpodcast** [comment]
Thanks for your quick reply.  So it sounds like there's no issue with me working on this.  I'd like to see how far I can take this and perhaps it can be useful down the road.  On a different note, thank you very much for starting the shinytest package!  It was featured at rstudio::conf and I can't wait to start using it in my apps.

**Comment by gaborcsardi** [comment]
I really want to write a proper package manager, but I'll probably write it from scratch, and not continue this repo.

**Comment by rpodcast** [comment]
It's been on my wish list for a long time too.  If you don't mind I'll start a new repository and begin building this up bit by bit.  I'd welcome your feedback on features you'd like to see.  My aim is to take the best features of various Linux package managers and build functionality to keep track of updates to non-CRAN packages (i.e. from GitHub or other remotes) in addition to CRAN packages.

**Comment by gaborcsardi** [comment]
See the invitation for a repo with some notes I made about this. Although I might have changed my opinion about these issues since then. :)
